//in this project,we will use a maths function to generate a number by computer and we will guess the number.
//here ,we are going to use the concept of loops to guess the correct number.
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<time.h>
int main()
{
    //creating variables to store input.
    int random_number,user_guess,tries=0;
    //to reset the random number generator.
    srand(time(NULL));
    //to generate a random number bw 1 and 1000.we can change it by any value in place of 1000.
    random_number=(rand()%1000)+1;
    printf("Enter a guess for the number generated by computer");
    //loop to guess number again and again.
    do{
        scanf("%d",&user_guess);
        if(user_guess>random_number)
        {
            printf("Guess a smaller number");
            tries++;
        }
        else if(user_guess<random_number)
        {
            printf("Guess a large number");
            tries++;
        }
        else
        {
            printf("Congrats!!You guessed the right number=%d in %d tries",random_number,tries);
        }
    }
    while(user_guess!=random_number);  
}